- id: '1702162974393'
  alias: Test Washer ppower
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: b62f3f8980208f7d3f115891794c1cd9
    entity_id: 9833777ac201ef47c1929e11d761e0cf
    domain: sensor
    below: 10
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_seafoam
    data:
      message: Washer is done
  - service: notify.living_room_tv
    metadata: {}
    data:
      message: Washer is Done
  mode: single
- id: '1702330079865'
  alias: Dryer test
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: cb60d003ff7ed868603fb5eca1b291fb
    entity_id: 0ed1bfa8f7a51697825ee542d3fd3e2e
    domain: binary_sensor
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_kevin_phone
    data:
      message: 'Dryer done '
  mode: single
- id: '1702931883959'
  alias: Fireplace webhook
  description: ''
  trigger:
  - platform: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: fireplace-on
  condition: []
  action:
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.fireplace
    data:
      hvac_mode: heat
  mode: single
- id: '1712973614098'
  alias: Test switch for yard
  description: ''
  triggers:
  - type: turned_on
    device_id: 8681549325fdea02e6ae53f143706e38
    entity_id: 3f807357d04058d7321f3f1f4c82de74
    domain: switch
    id: upper-on
    trigger: device
  - type: turned_off
    device_id: 8681549325fdea02e6ae53f143706e38
    entity_id: 3f807357d04058d7321f3f1f4c82de74
    domain: switch
    id: upper-off
    trigger: device
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - upper-on
      sequence:
      - metadata: {}
        data: {}
        action: switch.turn_on
        target:
          entity_id: switch.yard_plugs_yard_lights
    - conditions:
      - condition: trigger
        id:
        - upper-off
      sequence:
      - metadata: {}
        data: {}
        action: switch.turn_off
        target:
          entity_id: switch.yard_plugs_yard_lights
  mode: single
- id: '1725573985458'
  alias: Doorbell light flash
  description: ''
  trigger:
  - platform: state
    entity_id:
    - event.front_door_chime
  condition: []
  action:
  - repeat:
      count: 3
      sequence:
      - device_id: 07f29ac5c75cce573c0a49fd078cad06
        domain: light
        entity_id: f874c555d6722f9128efc0d5a0b02d97
        type: flash
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
  mode: single
- id: '1732942429267'
  alias: Tower Group Control
  description: ''
  triggers:
  - type: turned_on
    device_id: 5513781073db08c770d9a82e4510555b
    entity_id: 5ac8048d1f1934a81ff28820c5c38bbf
    domain: light
    trigger: device
    id: tower_on
  - type: turned_off
    device_id: 5513781073db08c770d9a82e4510555b
    entity_id: 5ac8048d1f1934a81ff28820c5c38bbf
    domain: light
    trigger: device
    id: tower_off
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - tower_on
      sequence:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          area_id: tower
    - conditions:
      - condition: trigger
        id:
        - tower_off
      sequence:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          area_id: tower
  mode: single
- id: '1737362705147'
  alias: Printer Status Bar
  description: ''
  triggers:
  - trigger: state
    id: percent_update
    entity_id:
    - sensor.print_job_completion
    not_from:
    - unknown
    - unavailable
    not_to:
    - unknown
    - unavailable
    - '100'
  - trigger: state
    id: print_complete
    entity_id:
    - sensor.saturn_4_ultra_print_status
    to: complete
    not_from:
    - unknown
    - unavailable
  - trigger: state
    id: print_error
    entity_id:
    - sensor.saturn_4_ultra_print_status
    to:
    - unknown
    - unavailable
    not_from:
    - complete
    - idle
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - percent_update
      sequence:
      - action: notify.mobile_app_kevin_pixel_8
        metadata: {}
        data:
          message: '{{states(''sensor.print_job_completion'')}}%'
          title: Saturn 4 Ultra
          data:
            tag: saturn_4_ultra_current_layer
            channel: Printer Status Bar
            importance: min
    - conditions:
      - condition: trigger
        id:
        - print_error
      sequence:
      - action: notify.mobile_app_kevin_pixel_8
        metadata: {}
        data:
          title: Saturn 4 Ultra
          message: Print Failed!
          data:
            tag: saturn_4_ultra_status
            channel: Print Error
            importance: default
    - conditions:
      - condition: trigger
        id:
        - print_complete
      sequence:
      - action: notify.mobile_app_kevin_pixel_8
        metadata: {}
        data:
          message: clear_notification
          data:
            tag: saturn_4_ultra_current_layer
      - action: notify.mobile_app_kevin_pixel_8
        metadata: {}
        data:
          title: Saturn 4 Ultra
          message: Print Complete!
          data:
            tag: saturn_4_ultra_status
            channel: Print Complete
            importance: default
  mode: single
