- id: '1702162974393'
  alias: Test Washer ppower
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: b62f3f8980208f7d3f115891794c1cd9
    entity_id: 9833777ac201ef47c1929e11d761e0cf
    domain: sensor
    below: 10
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_seafoam
    data:
      message: Washer is done
  - service: notify.living_room_tv
    metadata: {}
    data:
      message: Washer is Done
  mode: single
- id: '1702330079865'
  alias: Dryer test
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: cb60d003ff7ed868603fb5eca1b291fb
    entity_id: 0ed1bfa8f7a51697825ee542d3fd3e2e
    domain: binary_sensor
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_kevin_phone
    data:
      message: 'Dryer done '
  mode: single
- id: '1702931883959'
  alias: Fireplace webhook
  description: ''
  trigger:
  - platform: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: fireplace-on
  condition: []
  action:
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.fireplace
    data:
      hvac_mode: heat
  mode: single
- id: '1712973614098'
  alias: Test switch for yard
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 8681549325fdea02e6ae53f143706e38
    entity_id: 3f807357d04058d7321f3f1f4c82de74
    domain: switch
    id: upper-on
  - platform: device
    type: turned_off
    device_id: 8681549325fdea02e6ae53f143706e38
    entity_id: 3f807357d04058d7321f3f1f4c82de74
    domain: switch
    id: upper-off
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - upper-on
      sequence:
      - service: switch.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: switch.tp_link_smart_plug_46a3_yard_lights
    - conditions:
      - condition: trigger
        id:
        - upper-off
      sequence:
      - service: switch.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: switch.tp_link_smart_plug_46a3_yard_lights
  mode: single
- id: '1725573985458'
  alias: Doorbell light flash
  description: ''
  trigger:
  - platform: state
    entity_id:
    - event.front_door_chime
  condition: []
  action:
  - repeat:
      count: 3
      sequence:
      - device_id: 07f29ac5c75cce573c0a49fd078cad06
        domain: light
        entity_id: f874c555d6722f9128efc0d5a0b02d97
        type: flash
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
  mode: single
