homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  time_zone: "America/Vancouver"
  unit_system: metric
  external_url: !secret home_external_url

  # Load configs in logical groups
  packages: !include_dir_named packages

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

####################  Services  ####################
# HTTP/SSL
http:
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

# Text to speech
tts:
  - platform: google_translate

# Alexa
alexa:
  smart_home:
    locale: en-CA
    endpoint: https://api.amazonalexa.com/v3/events
    client_id: !secret alexa_client_id
    client_secret: !secret alexa_client_secret
    filter:
      include_domains:
        - climate
        - light
        - lock
        - vacuum
      exclude_entities:
        - climate.fireplace
        - light.katie_desk_light
        - light.kevin_status_lights

alexa_media:
  accounts:
    - email: !secret amazon_email
      password: !secret amazon_password
      url: amazon.ca
      exclude_devices:
        - "This Device"

# Google Assistant
google_assistant:
  project_id: !secret google_project_id
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  secure_devices_pin: !secret google_secure_devices_pin
  expose_by_default: false
