homeassistant:
  customize:
    event.status_cube_1:
      friendly_name: Status Cube Side 1
      icon: mdi:dice-1
    event.status_cube_2:
      friendly_name: Status Cube Side 2
      icon: mdi:dice-2
    event.status_cube_3:
      friendly_name: Status Cube Side 3
      icon: mdi:dice-3
    event.status_cube_4:
      friendly_name: Status Cube Side 4
      icon: mdi:dice-4
    event.status_cube_5:
      friendly_name: Status Cube Side 5
      icon: mdi:dice-5
    event.status_cube_6:
      friendly_name: Status Cube Side 6
      icon: mdi:dice-6
