# Automated control of the climate devices via smart thermostats
##############################################################

automation:
  - id: fireplace_unattended
    alias: π - RULE - Fireplace Unattended
    description: "Turns off the fireplace is there is no one on the main level for a while"
    mode: single
    trigger:
      - platform: template
        value_template: >
          {{ is_state('climate.fireplace', 'heat') and is_state('binary_sensor.main_level_presence', 'off') }}
        for:
          hours: 0
          minutes: 10
          seconds: 0
    action:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.fireplace
        data:
          hvac_mode: "off"
  ############################################################
  - id: heat_pump_mutex
    alias: π - RULE - Heat Pump Mutex
    trigger:
      - id: bedroom_cool
        platform: state
        entity_id: climate.bedroom_thermostat
        to: "cool"
      - id: bedroom_heat
        platform: state
        entity_id: climate.bedroom_thermostat
        to: "heat"
      - id: living_room_cool
        platform: state
        entity_id: climate.living_room_thermostat
        to: "cool"
      - id: living_room_heat
        platform: state
        entity_id: climate.living_room_thermostat
        to: "heat"
    action:
      - choose:
          - conditions:
              - or:
                  - and:
                      - condition: trigger
                        id:
                          - bedroom_cool
                      - condition: state
                        entity_id: climate.living_room_thermostat
                        state: "heat"
                  - and:
                      - condition: trigger
                        id:
                          - bedroom_heat
                      - condition: state
                        entity_id: climate.living_room_thermostat
                        state: "cool"
            sequence:
              - service: climate.turn_off
                target:
                  entity_id: climate.living_room_thermostat
          - conditions:
              - or:
                  - and:
                      - condition: trigger
                        id:
                          - living_room_cool
                      - condition: state
                        entity_id: climate.bedroom_thermostat
                        state: "heat"
                  - and:
                      - condition: trigger
                        id:
                          - living_room_heat
                      - condition: state
                        entity_id: climate.bedroom_thermostat
                        state: "cool"
            sequence:
              - service: climate.turn_off
                target:
                  entity_id: climate.bedroom_thermostat
  ############################################################
