# Automated control of the fireplace via smart thermostat
##############################################################

automation:
  - id: fireplace_unattended
    alias: Fireplace Unattended
    description: "Turns off the fireplace is there is no one on the main level for a while"
    mode: single
    trigger:
      - platform: template
        value_template: >
          {{ is_state('climate.fireplace', 'heat') and is_state('binary_sensor.main_level_presence', 'off') }}
        for:
          hours: 0
          minutes: 10
          seconds: 0
    action:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.fireplace
        data:
          hvac_mode: "off"
