# Control the garage doors
##############################################################

automation:
  - id: garage_door_tag
    alias: TAG - Garage Door
    mode: single
    trigger:
      - platform: tag
        tag_id: 69d8d98d-700e-4e8c-ac10-85a2165badaf
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: cover.garage_door
                state: "closed"
              - condition: state
                entity_id: binary_sensor.inner_garage_door
                state: "off"
            sequence:
              - service: cover.open_cover
                target:
                  entity_id: cover.garage_door
          - conditions:
              - not:
                  - condition: state
                    entity_id: cover.garage_door
                    state: "closed"
            sequence:
              - service: cover.close_cover
                target:
                  entity_id: cover.garage_door
      - delay:
          seconds: 2
  ############################################################
  - id: garage_door_lock
    alias: Ï€ - RULE - Auto-lock Garage Door
    mode: single
    trigger:
      - platform: state
        entity_id: cover.garage_door
        from: "closed"
    condition:
      - condition: state
        entity_id: binary_sensor.inner_garage_door
        state: "off"
    action:
      - service: lock.lock
        target:
          entity_id: lock.garage_door
  ############################################################
  - id: garage_door_driving
    alias: Open Garage Door When Driving Home
    mode: single
    trigger:
      - id: katie_home
        platform: zone
        entity_id: person.katie
        zone: zone.home
        event: enter
      - id: kevin_home
        platform: zone
        entity_id: person.kevin
        zone: zone.home
        event: enter
    condition:
      - or:
          - and:
              - condition: trigger
                id:
                  - katie_home
              - condition: state
                entity_id: binary_sensor.seafoam_android_auto
                state: "on"
          - and:
              - condition: trigger
                id:
                  - kevin_home
              - condition: state
                entity_id: binary_sensor.kevin_phone_android_auto
                state: "on"
      - condition: state
        entity_id: binary_sensor.inner_garage_door
        state: "off"
    action:
      - service: cover.open_cover
        target:
          entity_id: cover.garage_door
  ############################################################
