# Sync exposed devices to the voice assistants
##############################################################

automation:
  - id: sync_devices
    alias: Σ - SYSTEM - Sync Devices to Assistants
    mode: single
    triggers:
      - trigger: homeassistant
        event: start
    actions:
      - action: google_assistant.request_sync
        data:
          agent_user_id: !secret google_agent_user_id
      - action: media_player.play_media
        target:
          entity_id: media_player.echo_pop
        data:
          media_content_type: custom
          media_content_id: Discover devices
  ############################################################
